version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortl-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shortl-db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  bot:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/shortl-db"
      BOT_TOKEN: "7869214296:AAEw8hgTR2gOD8W8z3gFlSgfcyvyek9bme4"
    restart: always
 
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
  
  payment:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    command: python web/payment_server.py
    ports:
      - "5005:5005"

volumes:
  postgres_data:

